CodingTest/성호/2주차/BFS/11967(불 켜기).js, CodingTest/성호/2주차/BFS/1926(그림).js, CodingTest/성호/2주차/BFS/2573(빙산).js, CodingTest/성호/2주차/DFS/13023(ABCDE).js, CodingTest/성호/2주차/DFS/24479(알고리즘 수업 - 깊이우선탐색1).js, CodingTest/성호/2주차/기타/1260(BFS와DFS).js
=> [week02] 손성호

CodingTest/이수하/2주차/코테/다리만들기.java
이번주 목금토일 여행 및 개인일정으로 한문제도 못 풀었습니다 죄송합니다
=> [week4] 이수하

CodingTest/성호/5주차/그래프/1389(케빈 베이컨의 6단계 법칙).js, CodingTest/성호/5주차/그래프/1707(이분 그래프).js, CodingTest/성호/5주차/그래프/README.md, CodingTest/성호/5주차/트리/1967(트리의 지름).js, CodingTest/성호/5주차/트리/1991(트리 순회).js, CodingTest/성호/5주차/트리/README.md
=> [week05] 손성호

CodingTest/이수하/6주차/백트래킹/로또.java, CodingTest/이수하/6주차/백트래킹/무기공학.java, CodingTest/이수하/6주차/백트래킹/풀이.md
=> [week06] 이수하

CodingTest/한종민/8주차/README.md, CodingTest/한종민/8주차/기타/성적평균.java, CodingTest/한종민/8주차/좋다.java
다른 소프티어 문제 푼다고 두 문제 밖에 못 풀었습니당..
=> [week08] 한종민

CodingTest/한종민/9주차/구현/README.md, CodingTest/한종민/9주차/구현/배열돌리기1.java, CodingTest/한종민/9주차/투포인터/README.md, CodingTest/한종민/9주차/투포인터/가장_긴_짝수_연속한_부분_수열(large).java, CodingTest/한종민/9주차/투포인터/회전초밥.java
=> [week09] 한종민

CodingTest/한종민/11주차/README.md, CodingTest/한종민/11주차/볼 모으기.java, CodingTest/한종민/11주차/시험감독.java, CodingTest/한종민/11주차/진우의 달여행(small).java, CodingTest/한종민/11주차/하늘에서 별똥별이 빗발친다.java
=> [week11] 한종민

CodingTest/이수하/11주차/DFS/진우의 달 여행_17484.java, CodingTest/이수하/11주차/DFS/풀이.md, CodingTest/이수하/11주차/그리디/불모으기_17615.java, CodingTest/이수하/11주차/그리디/풀이.md, CodingTest/이수하/11주차/브르투포스/풀이.md, CodingTest/이수하/11주차/브르투포스/하늘에서 별똥별이 빗발친다_14658.java, CodingTest/이수하/11주차/사칙연산/시험 감독_13458.java, CodingTest/이수하/11주차/사칙연산/풀이.md
=> [week11] 이수하

CodingTest/이수하/12주차/구현, 시뮬레이션/지구온난화_5212.java, CodingTest/이수하/12주차/구현, 시뮬레이션/풀이.md, CodingTest/이수하/12주차/수학,문자열/이 구역의 승자는 누구야?!_20154.java, CodingTest/이수하/12주차/수학,문자열/풀이.md
=> [week12] 이수하

CodingTest/성호/12주차/1292(쉽게 푸는 문제).js, CodingTest/성호/12주차/1806(부분 합).js, CodingTest/성호/12주차/6443(애너그램).js, CodingTest/성호/12주차/README.md
가르침의 경우 노드로 안풀려서 패스했습니다. (메모리 초과관련)
여자처자 푼사람이 있는데, 코드가 그냥 이해가 안되는.. 수준입니다 ㅠ
https://parkparkpark.tistory.com/113
=> [week13] 손성호

CodingTest/성유진/13주차/README.md, CodingTest/성유진/13주차/가르침.java, CodingTest/성유진/13주차/부분합.java, CodingTest/성유진/13주차/쉽게푸는문제.java, CodingTest/성유진/13주차/애너그램.java, CodingTest/성유진/13주차/애너그램2.java
=> [week13] 성유진

CodingTest/이수하/13주차/모의코테/퍼즐 게임 챌린지.java, CodingTest/이수하/13주차/백트래킹/가르침_1062.java, CodingTest/이수하/13주차/수학,구현/쉽게 푸는 문제_1292.java, CodingTest/이수하/9주차/투포인터/풀이.md
=> [week13] 이수하

CodingTest/성호/13주차/1182(부분수열의 합).js, CodingTest/성호/13주차/16987(계란으로 바위치기).js, CodingTest/성호/13주차/22944(죽음의 비).js, CodingTest/성호/13주차/2580(스도쿠).js, CodingTest/성호/13주차/README.md
=> [week 14] 손성호

CodingTest/이수하/14주차/백트래킹/계란으로 계란치기_16987.java, CodingTest/이수하/14주차/백트래킹/부분수열의합_1182.java, CodingTest/이수하/14주차/백트래킹/풀이.md
=>  [week 14] 이수하

CodingTest/성호/14주차/15665(N과 M (11)).js, CodingTest/성호/14주차/1600(말이 되고픈 원숭이).js, CodingTest/성호/14주차/3980(선발 명단).js, CodingTest/성호/14주차/5014(스타트링크).js, CodingTest/성호/14주차/README.md
=> [week15] 손성호

CodingTest/성호/15주차/10942(팰린드롬 ?).js, CodingTest/성호/15주차/12866(돌 그룹).js, CodingTest/성호/15주차/16954(움직이는 미로 탈출).js, CodingTest/성호/15주차/2831(댄스 파티).js, CodingTest/성호/15주차/README.md
=> [week 16] 손성호

CodingTest/한종민/16주차/README.md, CodingTest/한종민/16주차/댄스파티.java, CodingTest/한종민/16주차/돌그룹.java, CodingTest/한종민/16주차/움직이는 미로 탈출.java, CodingTest/한종민/16주차/펠린드롬.java
=> [week16] 한종민

CodingTest/한종민/17주차/단축키 지정.java, CodingTest/한종민/17주차/랭킹전 대기열.java, CodingTest/한종민/17주차/문자열 게임2.java, CodingTest/한종민/17주차/문자열 교환.java
리드미는 다 써놧는데.. 커밋 취소하다가.. 파일을 다 날려서 없어졋습니다.. 
빠르게 업데이트 하겟숩니당 ㅠ
=> [week17] 한종민

CodingTest/성호/16주차/1283(단축키 지정).js, CodingTest/성호/16주차/1522(문자열 교환).js, CodingTest/성호/16주차/20006(랭킹전 대기열).js, CodingTest/성호/16주차/20437(문자열 게임 2).js, CodingTest/성호/16주차/README.md
=> [week17] 손성호

CodingTest/성호/17주차/11725(트리의 부모 찾기).js, CodingTest/성호/17주차/1325(효율적인 해킹).js, CodingTest/성호/17주차/15683(감시).js, CodingTest/성호/17주차/2665(미로 만들기).js, CodingTest/성호/17주차/README.md
=> [week18] 손성호

CodingTest/이수하/19주차/dfs/A와B2_12919.java, CodingTest/이수하/19주차/dfs/풀이.md, CodingTest/이수하/19주차/구현/디지털티비_2816.java, CodingTest/이수하/19주차/구현/풀이.md, CodingTest/이수하/19주차/모의코테/여행경로.java, CodingTest/이수하/19주차/이분탐색/공유기설치_2110.java, CodingTest/이수하/19주차/이분탐색/풀이.md
=> [WEEK19] 이수하

CodingTest/성호/18주차/12919(A와 B 2).js, CodingTest/성호/18주차/1520(내리막 길).js, CodingTest/성호/18주차/2110(공유기 설치).js, CodingTest/성호/18주차/2816(디지털 티비).js, CodingTest/성호/18주차/README.md
=> [WEEK19] 손성호

CodingTest/성호/19주차/1174(줄어드는 수).js, CodingTest/성호/19주차/14712(넴모넴모 (Easy)).js, CodingTest/성호/19주차/14888(연산자 끼워넣기).js, CodingTest/성호/19주차/3079(입국심사).js, CodingTest/성호/19주차/README.md
=> [week20] 손성호

CodingTest/성호/20주차/README.md, CodingTest/성호/20주차/네트워크.js, CodingTest/성호/20주차/숫자게임.js, CodingTest/성호/20주차/인사고과.js, CodingTest/성호/20주차/지게차와 크레인.js
=> [week21] 손성호
